language: node_js
node_js:
  - "node"
install:
  - npm install -g codecov
  - npm install -g mocha
  - npm install -g nyc
services:
  - postgres
env:
  global: CC_TEST_REPORTER_ID=2a61f24def1e61b131a9e06e7590328a9164cb5a3029fbe738316ab15b671512
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
cache:
  directories:
    - "node_modules"
after_success:
  - npm run coverage