language: node_js
node_js:
  - "stable"
install:
  - npm install -g codecov
notifications:
  email: false
services:
  - postgresql
env:
  global: CC_TEST_REPORTER_ID=9f1dee3aefbaa0a9fa39c80b338d45c789469a5c7abcd44c4637be7a4d2a9ac5
script: 
  - npm run test
before_script:
  - npm install
  - psql -c 'create database travis_ci_test;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
cache:
  directories:
    - "node_modules"
after_success:
  - npm run coverage
